services:
  - type: web
    name: excel-backend
    env: python
    repo: https://github.com/shlokrgs/excel-dashboard
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free

  - type: web
    name: excel-frontend
    env: python
    repo: https://github.com/shlokrgs/excel-dashboard
    branch: main
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    plan: free
